language: python
python:
  - "2.7"
install: 
  - pip install -r requirements.txt
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/tests
  - cd tests
  - export PYTHONPATH=$PYTHONPATH:..:.
  - export FGAPISRV_NOTOKEN=True
  - export FGAPISRV_NOTOKENUSR=test
  - python -m unittest test_mklogtoken
  - python -m unittest test_fgapiserverconfig
  - python -m unittest test_fgapiserver

branches:
  only:
    - EnvConfig
