language: python
python:
  - "2.7"
  - "3.7"
install: 
  - pip install -r requirements.txt
  - pip install pycodestyle
script:
  - pycodestyle --ignore=E402 *.py
  - cd tests
  - pycodestyle *.py
  - export FGTESTS_STOPATFAIL=1
  - export PYTHONPATH=$PYTHONPATH:..:.
  - export FGAPISRV_NOTOKEN=True
  - export FGAPISRV_NOTOKENUSR=test
  - python -m unittest test_mklogtoken
  - python -m unittest test_fgapiserverconfig
  - python -m unittest test_fgapiserver
  - export FGAPISRV_NOTOKEN=False
  - export FGAPISRV_LNKPTVFLAG=False
  - python -m unittest test_auth
  - python -m unittest test_users_apis
  - echo "fgapiserver.log"
  - cat fgapiserver.log
branches:
  only:
    - py2py3 
